/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package credit.calification.views;

import credit.calification.controllers.EventHandler;
import credit.calification.controllers.MotorController;
import credit.calification.controllers.CreditController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import jess.JessException;
import java.net.URL;
import java.net.URLEncoder;
import javax.swing.JOptionPane;


/**
 *
 * @author Kattya Desiderio
 */
public class AplicationForm extends javax.swing.JFrame {

    private MotorController motorController;
    String edad,tuvoCreditos,montoBajo,montoAlto,plazoBajo,plazoAlto;
    String poseeTarjetaCredito,pagaATiempo,frecuenciaUsoTC,estadoCivil;
    String femenino,masculino,soltero,casado;
 
    
    public AplicationForm() {
        initComponents();
        
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_CI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_femenino = new javax.swing.JRadioButton();
        btn_masculino = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        btn_soltero = new javax.swing.JRadioButton();
        btn_casado = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        btn_enviar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        cb_poseeTarjetaCredito = new javax.swing.JCheckBox();
        cb_montoAlto = new javax.swing.JCheckBox();
        cb_montoBajo = new javax.swing.JCheckBox();
        btn_check = new javax.swing.JButton();
        cb_plazoBajo = new javax.swing.JCheckBox();
        cb_frecuenciaUsoTC = new javax.swing.JCheckBox();
        cb_tuvoCreditos = new javax.swing.JCheckBox();
        cb_pagaATiempo = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        cb_plazoAlto = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(743, 743));
        setSize(new java.awt.Dimension(743, 743));
        getContentPane().setLayout(null);
        getContentPane().add(txt_CI);
        txt_CI.setBounds(140, 110, 136, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CI / RUC:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 70, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("If the answer is NO leave the square in blank");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 300, 290, 17);
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(140, 140, 227, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Surname:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 170, 60, 17);
        getContentPane().add(txt_apellido);
        txt_apellido.setBounds(140, 170, 228, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Age:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 200, 40, 17);

        txt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edadActionPerformed(evt);
            }
        });
        getContentPane().add(txt_edad);
        txt_edad.setBounds(140, 200, 50, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Location:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 230, 57, 17);

        txt_direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_direccion.setAutoscrolls(false);
        txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_direccion);
        txt_direccion.setBounds(140, 230, 222, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel9.setText("Credit Application ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(120, 20, 387, 58);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Sex:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(520, 100, 40, 20);

        btn_femenino.setText("Female");
        btn_femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_femeninoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_femenino);
        btn_femenino.setBounds(560, 103, 90, 20);

        btn_masculino.setText("Male");
        getContentPane().add(btn_masculino);
        btn_masculino.setBounds(560, 123, 93, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Marital status:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(450, 150, 110, 17);

        btn_soltero.setText("Single");
        btn_soltero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solteroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_soltero);
        btn_soltero.setBounds(560, 153, 70, 20);

        btn_casado.setText("Married");
        getContentPane().add(btn_casado);
        btn_casado.setBounds(560, 173, 93, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText(" Credit references");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 270, 210, 17);

        btn_enviar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_enviar.setText("Send");
        btn_enviar.setToolTipText("");
        btn_enviar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_enviar.setName("btn_enviar"); // NOI18N
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_enviar);
        btn_enviar.setBounds(530, 440, 90, 27);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 310, 110, 0);

        cb_poseeTarjetaCredito.setText("Has credit cards?");
        getContentPane().add(cb_poseeTarjetaCredito);
        cb_poseeTarjetaCredito.setBounds(100, 500, 200, 23);

        cb_montoAlto.setText("amount equals or greater than 31 000");
        cb_montoAlto.setToolTipText("");
        cb_montoAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_montoAltoActionPerformed(evt);
            }
        });
        getContentPane().add(cb_montoAlto);
        cb_montoAlto.setBounds(130, 380, 230, 23);

        cb_montoBajo.setText("amount equals or less than 30 000");
        cb_montoBajo.setToolTipText("");
        cb_montoBajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_montoBajoActionPerformed(evt);
            }
        });
        getContentPane().add(cb_montoBajo);
        cb_montoBajo.setBounds(130, 360, 210, 23);

        btn_check.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_check.setText("Check");
        btn_check.setToolTipText("Validate the information within the credit bureau");
        btn_check.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkActionPerformed(evt);
            }
        });
        getContentPane().add(btn_check);
        btn_check.setBounds(530, 480, 90, 31);

        cb_plazoBajo.setText("credit term equals or less than 10 years*");
        cb_plazoBajo.setToolTipText("");
        cb_plazoBajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_plazoBajoActionPerformed(evt);
            }
        });
        getContentPane().add(cb_plazoBajo);
        cb_plazoBajo.setBounds(130, 410, 230, 23);

        cb_frecuenciaUsoTC.setText("Uses them often?*");
        cb_frecuenciaUsoTC.setToolTipText("");
        cb_frecuenciaUsoTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_frecuenciaUsoTCActionPerformed(evt);
            }
        });
        getContentPane().add(cb_frecuenciaUsoTC);
        cb_frecuenciaUsoTC.setBounds(140, 530, 170, 23);

        cb_tuvoCreditos.setText("had a previous bank loan?*");
        cb_tuvoCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tuvoCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(cb_tuvoCreditos);
        cb_tuvoCreditos.setBounds(100, 330, 170, 23);

        cb_pagaATiempo.setText("Make payments before deadline*");
        getContentPane().add(cb_pagaATiempo);
        cb_pagaATiempo.setBounds(100, 470, 200, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Name:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 140, 40, 17);

        cb_plazoAlto.setText("credit term equals or greater than 11 years*");
        cb_plazoAlto.setToolTipText("");
        cb_plazoAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_plazoAltoActionPerformed(evt);
            }
        });
        getContentPane().add(cb_plazoAlto);
        cb_plazoAlto.setBounds(130, 430, 270, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edadActionPerformed

    private void txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionActionPerformed

    private void btn_femeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_femeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_femeninoActionPerformed

    private void btn_solteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solteroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_solteroActionPerformed

    public String getEdad(){
     String edadRaw = "OutLimits";
     int edad = 0;
     if(txt_edad.getText().equals("")){
         edadRaw = "OutLimits";
     }
     else{
     edad = Integer.parseInt(txt_edad.getText());
     if(edad > 21 && edad <= 37 ){
      edadRaw = "J";
     }
     else if (edad > 37 && edad <= 70 ){
         edadRaw = "A";
     }
     else if (edad < 0 || edad <21 || edad > 70){
         edadRaw = "OutLimits";
     }
     }
        return edadRaw;
    }
    
    public String getEstadoCivil(){
      String estadoCivil = "";
      soltero = Boolean.toString(btn_soltero.isSelected());
      casado = Boolean.toString(btn_casado.isSelected());
         if(soltero.equals("true") && casado.equals("false")){
         estadoCivil = "S";
     }
     else{
         estadoCivil = "C";
         }
      return estadoCivil;
    }
    
    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        
        edad = this.getEdad();        
        estadoCivil = this.getEstadoCivil();
        
        tuvoCreditos = Boolean.toString(cb_tuvoCreditos.isSelected());
        montoBajo = Boolean.toString(cb_montoBajo.isSelected());
        montoAlto = Boolean.toString(cb_montoAlto.isSelected());
        plazoBajo = Boolean.toString(cb_plazoBajo.isSelected());
        plazoAlto = Boolean.toString(cb_plazoAlto.isSelected());
        poseeTarjetaCredito = Boolean.toString(cb_poseeTarjetaCredito.isSelected());
        pagaATiempo = Boolean.toString(cb_pagaATiempo.isSelected());
        frecuenciaUsoTC = Boolean.toString(cb_frecuenciaUsoTC.isSelected());
        femenino = Boolean.toString(btn_femenino.isSelected());
        masculino = Boolean.toString(btn_masculino.isSelected());
        
        
        String hecho = "";
        
        try {
            if (edad.equals("OutLimits")){
                JOptionPane.showMessageDialog(null, "Age not permited","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            }
            else{
            //(= ?frecuenciaUsoTC false) (= ?pagaATiempo true) (= ?plazoBajo true) (= ?edad J) (= ?estadoCivil C)(= ?poseeTarjetaCredito true) 
            hecho = "(credit-calification "+
                    "(frecuenciaUsoTC "+ frecuenciaUsoTC + ")"+
                    "(pagaATiempo "+ pagaATiempo + ")"+
                    "(plazoAlto "+ plazoAlto + ")"+
                    "(plazoBajo "+ plazoBajo + ")"+
                    "(tuvoCreditos "+  tuvoCreditos + ")"+
                    "(edad "+ edad + ")"+
                    "(estadoCivil "+ estadoCivil + ")"+
                    "(poseeTarjetaCredito "+ poseeTarjetaCredito + ")"+
                    "(montoAlto "+ montoAlto + ")"+
                    "(montoBajo "+ montoBajo + ")"+
                    ")";
           
//            System.out.println(hecho);
            this.motorController.afirmar(hecho);
            }
           
        } catch (JessException ex) {
            Logger.getLogger(AplicationForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_enviarActionPerformed

    private void cb_montoAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_montoAltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_montoAltoActionPerformed

    private void cb_montoBajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_montoBajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_montoBajoActionPerformed

    private void btn_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkActionPerformed

    }//GEN-LAST:event_btn_checkActionPerformed

    private void cb_plazoBajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_plazoBajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_plazoBajoActionPerformed

    private void cb_frecuenciaUsoTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_frecuenciaUsoTCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_frecuenciaUsoTCActionPerformed

    private void cb_plazoAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_plazoAltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_plazoAltoActionPerformed

    private void cb_tuvoCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tuvoCreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tuvoCreditosActionPerformed
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicationForm().setVisible(true);
                
            }
        });
    }
    public void setMotorController(MotorController motorController){
        this.motorController = motorController;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn_casado;
    private javax.swing.JButton btn_check;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JRadioButton btn_femenino;
    private javax.swing.JRadioButton btn_masculino;
    private javax.swing.JRadioButton btn_soltero;
    private javax.swing.JCheckBox cb_frecuenciaUsoTC;
    private javax.swing.JCheckBox cb_montoAlto;
    private javax.swing.JCheckBox cb_montoBajo;
    private javax.swing.JCheckBox cb_pagaATiempo;
    private javax.swing.JCheckBox cb_plazoAlto;
    private javax.swing.JCheckBox cb_plazoBajo;
    private javax.swing.JCheckBox cb_poseeTarjetaCredito;
    private javax.swing.JCheckBox cb_tuvoCreditos;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_CI;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
