package credit.calification.views;

import credit.calification.controllers.EventHandler;
import credit.calification.controllers.MotorController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import jess.JessException;
import java.net.URL;
import java.net.URLEncoder;
import javax.swing.JOptionPane;


/**
 * Grupo 10: 
 * @author: Kattya Desiderio
 * @author: Stephany Quimba
 * @author: Joyce Sarmiento
 * @version: 06/02/2016/
 */

public class AplicationForm extends javax.swing.JFrame {

    public MotorController motorController;
    String edad,tuvoCreditos,montoBajo,montoAlto,plazoBajo,plazoAlto;
    String poseeTarjetaCredito,pagaATiempo,frecuenciaUsoTC,estadoCivil;
    String femenino,masculino,soltero,casado;
 
    
    public AplicationForm(MotorController motorController){
        initComponents();
        cb_montoBajo.setEnabled(false);
        cb_montoAlto.setEnabled(false);
        cb_plazoBajo.setEnabled(false);
        cb_plazoAlto.setEnabled(false);
        cb_frecuenciaUsoTC.setEnabled(false); 
        btn_casado.setEnabled(false);
        btn_masculino.setEnabled(false);
        this.motorController = motorController;
       
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_CI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_femenino = new javax.swing.JRadioButton();
        btn_masculino = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        btn_soltero = new javax.swing.JRadioButton();
        btn_casado = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        btn_enviar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        cb_poseeTarjetaCredito = new javax.swing.JCheckBox();
        cb_montoAlto = new javax.swing.JCheckBox();
        cb_montoBajo = new javax.swing.JCheckBox();
        cb_plazoBajo = new javax.swing.JCheckBox();
        cb_frecuenciaUsoTC = new javax.swing.JCheckBox();
        cb_tuvoCreditos = new javax.swing.JCheckBox();
        cb_pagaATiempo = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        cb_plazoAlto = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(743, 743));
        setSize(new java.awt.Dimension(743, 743));
        getContentPane().setLayout(null);
        getContentPane().add(txt_CI);
        txt_CI.setBounds(140, 110, 230, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CI / RUC:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 70, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("If the answer is NO leave the square in blank");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 350, 290, 17);
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(140, 150, 227, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Surname:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 200, 60, 17);
        getContentPane().add(txt_apellido);
        txt_apellido.setBounds(140, 190, 230, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Age:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 240, 40, 17);

        txt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edadActionPerformed(evt);
            }
        });
        getContentPane().add(txt_edad);
        txt_edad.setBounds(140, 230, 60, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Address:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 280, 57, 17);

        txt_direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_direccion.setAutoscrolls(false);
        txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_direccion);
        txt_direccion.setBounds(140, 270, 230, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel9.setText("Credit Application Form");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 20, 530, 58);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Sex:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(520, 100, 40, 20);

        btn_femenino.setText("Female");
        btn_femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_femeninoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_femenino);
        btn_femenino.setBounds(560, 103, 90, 20);

        btn_masculino.setText("Male");
        btn_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masculinoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_masculino);
        btn_masculino.setBounds(560, 123, 93, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Marital status:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(450, 150, 110, 17);

        btn_soltero.setText("Single");
        btn_soltero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solteroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_soltero);
        btn_soltero.setBounds(560, 153, 70, 20);

        btn_casado.setText("Married");
        btn_casado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_casadoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_casado);
        btn_casado.setBounds(560, 173, 93, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText(" Credit references");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(50, 320, 210, 17);

        btn_enviar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_enviar.setText("Send");
        btn_enviar.setToolTipText("");
        btn_enviar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_enviar.setName("btn_enviar"); // NOI18N
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_enviar);
        btn_enviar.setBounds(300, 630, 90, 27);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 310, 110, 0);

        cb_poseeTarjetaCredito.setText("Has credit cards?");
        cb_poseeTarjetaCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_poseeTarjetaCreditoActionPerformed(evt);
            }
        });
        getContentPane().add(cb_poseeTarjetaCredito);
        cb_poseeTarjetaCredito.setBounds(110, 550, 200, 23);

        cb_montoAlto.setText("amount equals or greater than 31 000");
        cb_montoAlto.setToolTipText("");
        cb_montoAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_montoAltoActionPerformed(evt);
            }
        });
        getContentPane().add(cb_montoAlto);
        cb_montoAlto.setBounds(140, 430, 230, 23);

        cb_montoBajo.setText("amount equals or less than 30 000");
        cb_montoBajo.setToolTipText("");
        cb_montoBajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_montoBajoActionPerformed(evt);
            }
        });
        getContentPane().add(cb_montoBajo);
        cb_montoBajo.setBounds(140, 410, 210, 23);

        cb_plazoBajo.setText("credit term equals or less than 10 years*");
        cb_plazoBajo.setToolTipText("");
        cb_plazoBajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_plazoBajoActionPerformed(evt);
            }
        });
        getContentPane().add(cb_plazoBajo);
        cb_plazoBajo.setBounds(140, 460, 230, 23);

        cb_frecuenciaUsoTC.setText("Uses them often?*");
        cb_frecuenciaUsoTC.setToolTipText("");
        cb_frecuenciaUsoTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_frecuenciaUsoTCActionPerformed(evt);
            }
        });
        getContentPane().add(cb_frecuenciaUsoTC);
        cb_frecuenciaUsoTC.setBounds(150, 580, 170, 23);

        cb_tuvoCreditos.setText("had a previous bank loan?*");
        cb_tuvoCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tuvoCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(cb_tuvoCreditos);
        cb_tuvoCreditos.setBounds(110, 380, 170, 23);

        cb_pagaATiempo.setText("Make payments before deadline*");
        getContentPane().add(cb_pagaATiempo);
        cb_pagaATiempo.setBounds(110, 520, 200, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Name:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 160, 40, 17);

        cb_plazoAlto.setText("credit term equals or greater than 11 years*");
        cb_plazoAlto.setToolTipText("");
        cb_plazoAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_plazoAltoActionPerformed(evt);
            }
        });
        getContentPane().add(cb_plazoAlto);
        cb_plazoAlto.setBounds(140, 480, 270, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edadActionPerformed

    private void txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionActionPerformed

    private void btn_femeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_femeninoActionPerformed
       String femenino = Boolean.toString(btn_femenino.isSelected());
        
        if(femenino.equals("false")){
            btn_masculino.setEnabled(true); 
        }
        else{
            btn_masculino.setEnabled(false);
        }
    }//GEN-LAST:event_btn_femeninoActionPerformed

    private void btn_solteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solteroActionPerformed
        String soltero = Boolean.toString(btn_soltero.isSelected());
        
        if(soltero.equals("false")){
            btn_casado.setEnabled(true); 
        }
        else{
            btn_casado.setEnabled(false);
        }
    }//GEN-LAST:event_btn_solteroActionPerformed

    public String getEdad(){
        String edadRaw = "OutLimits";
        int edad = 0;
        if(txt_edad.getText().equals("")){
            edadRaw = "OutLimits";
        }
        else{
        edad = Integer.parseInt(txt_edad.getText());
        if(edad > 21 && edad <= 37 ){
         edadRaw = "J";
        }
        else if (edad > 37 && edad <= 70 ){
            edadRaw = "A";
        }
        else if (edad < 0 || edad <21 || edad > 70){
            edadRaw = "OutLimits";
        }
        }
           return edadRaw;
    }
    
    public String getEstadoCivil(){
        String estadoCivil = "";
        soltero = Boolean.toString(btn_soltero.isSelected());
        casado = Boolean.toString(btn_casado.isSelected());
           if(soltero.equals("true") && casado.equals("false")){
           estadoCivil = "S";
       }
       else{
           estadoCivil = "C";
           }
        return estadoCivil;
    }
    
    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        
        edad = this.getEdad();        
        estadoCivil = this.getEstadoCivil();
        
        tuvoCreditos = Boolean.toString(cb_tuvoCreditos.isSelected());
        montoBajo = Boolean.toString(cb_montoBajo.isSelected());
        montoAlto = Boolean.toString(cb_montoAlto.isSelected());
        plazoBajo = Boolean.toString(cb_plazoBajo.isSelected());
        plazoAlto = Boolean.toString(cb_plazoAlto.isSelected());
        poseeTarjetaCredito = Boolean.toString(cb_poseeTarjetaCredito.isSelected());
        pagaATiempo = Boolean.toString(cb_pagaATiempo.isSelected());
        frecuenciaUsoTC = Boolean.toString(cb_frecuenciaUsoTC.isSelected());
        femenino = Boolean.toString(btn_femenino.isSelected());
        masculino = Boolean.toString(btn_masculino.isSelected());
        
        
        String hecho = "";
        
        try {
            if (edad.equals("OutLimits")){
                JOptionPane.showMessageDialog(null, "Age not permited","WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            }
            else{
            hecho = "(credit-calification "+
                    "(frecuenciaUsoTC "+ frecuenciaUsoTC + ")"+
                    "(pagaATiempo "+ pagaATiempo + ")"+
                    "(plazoAlto "+ plazoAlto + ")"+
                    "(plazoBajo "+ plazoBajo + ")"+
                    "(tuvoCreditos "+  tuvoCreditos + ")"+
                    "(edad "+ edad + ")"+
                    "(estadoCivil "+ estadoCivil + ")"+
                    "(poseeTarjetaCredito "+ poseeTarjetaCredito + ")"+
                    "(montoAlto "+ montoAlto + ")"+
                    "(montoBajo "+ montoBajo + ")"+
                    ")";

            this.motorController.afirmar(hecho);
            }
           
        } catch (JessException ex) {
            Logger.getLogger(AplicationForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_enviarActionPerformed

    private void cb_montoAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_montoAltoActionPerformed
       String montoAlto = Boolean.toString(cb_montoAlto.isSelected());
        
        if(montoAlto.equals("false")){
            cb_montoBajo.setEnabled(true); 
        }
        else{
            cb_montoBajo.setEnabled(false);
        }
    }//GEN-LAST:event_cb_montoAltoActionPerformed

    private void cb_montoBajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_montoBajoActionPerformed
        String montoBajo = Boolean.toString(cb_montoBajo.isSelected());
        
        if(montoBajo.equals("false")){
            cb_montoAlto.setEnabled(true); 
        }
        else{
            cb_montoAlto.setEnabled(false);
        }
    }//GEN-LAST:event_cb_montoBajoActionPerformed

    private void cb_plazoBajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_plazoBajoActionPerformed
       String plazoBajo = Boolean.toString(cb_plazoBajo.isSelected());
        
        if(plazoBajo.equals("false")){
            cb_plazoAlto.setEnabled(true); 
        }
        else{
            cb_plazoAlto.setEnabled(false);
        }
    }//GEN-LAST:event_cb_plazoBajoActionPerformed

    private void cb_frecuenciaUsoTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_frecuenciaUsoTCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_frecuenciaUsoTCActionPerformed

    private void cb_plazoAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_plazoAltoActionPerformed
      String plazoAlto = Boolean.toString(cb_plazoAlto.isSelected());
        
        if(plazoAlto.equals("false")){
            cb_plazoBajo.setEnabled(true); 
        }
        else{
            cb_plazoBajo.setEnabled(false);
        }
    }//GEN-LAST:event_cb_plazoAltoActionPerformed

    private void cb_tuvoCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tuvoCreditosActionPerformed
        String tuvoCredito = Boolean.toString(cb_tuvoCreditos.isSelected());
        
        if(tuvoCredito.equals("false")){
            cb_montoBajo.setEnabled(false);
            cb_montoAlto.setEnabled(false);
            cb_plazoBajo.setEnabled(false);
            cb_plazoAlto.setEnabled(false);
            
        }
        else{
            cb_montoBajo.setEnabled(true);
            cb_montoAlto.setEnabled(true);
            cb_plazoBajo.setEnabled(true);
            cb_plazoAlto.setEnabled(true);
        }
    }//GEN-LAST:event_cb_tuvoCreditosActionPerformed

    private void cb_poseeTarjetaCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_poseeTarjetaCreditoActionPerformed
        String poseeTarjetaCredito = Boolean.toString(cb_poseeTarjetaCredito.isSelected());
        
        if(poseeTarjetaCredito.equals("false")){
            cb_frecuenciaUsoTC.setEnabled(false); 
        }
        else{
            cb_frecuenciaUsoTC.setEnabled(true);
        }
    }//GEN-LAST:event_cb_poseeTarjetaCreditoActionPerformed

    private void btn_casadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_casadoActionPerformed
        String casado = Boolean.toString(btn_casado.isSelected());
        
        if(casado.equals("false")){
            btn_soltero.setEnabled(true); 
        }
        else{
            btn_soltero.setEnabled(false);
        }
    }//GEN-LAST:event_btn_casadoActionPerformed

    private void btn_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masculinoActionPerformed
        String masculino = Boolean.toString(btn_masculino.isSelected());
        
        if(masculino.equals("false")){
            btn_femenino.setEnabled(true); 
        }
        else{
            btn_femenino.setEnabled(false);
        }
    }//GEN-LAST:event_btn_masculinoActionPerformed
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AplicationForm().setVisible(true);
//                
//            }
//        });
    }
    
    public void setMotorController(MotorController motorController){
        this.motorController = motorController;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn_casado;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JRadioButton btn_femenino;
    private javax.swing.JRadioButton btn_masculino;
    private javax.swing.JRadioButton btn_soltero;
    private javax.swing.JCheckBox cb_frecuenciaUsoTC;
    private javax.swing.JCheckBox cb_montoAlto;
    private javax.swing.JCheckBox cb_montoBajo;
    private javax.swing.JCheckBox cb_pagaATiempo;
    private javax.swing.JCheckBox cb_plazoAlto;
    private javax.swing.JCheckBox cb_plazoBajo;
    private javax.swing.JCheckBox cb_poseeTarjetaCredito;
    private javax.swing.JCheckBox cb_tuvoCreditos;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_CI;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
